//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.19 at 11:47:11 PM EDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.eric.com/xml/todoapp", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.eric.xml.todoapp;
